AWSTemplateFormatVersion: "2010-09-09"
Description: Application Server with public ip
Parameters:
  DeploymentGroupName:
    Default: change-me
    Description: "Deployment Group Name"
    Type: String  
  ApplicationName:
    Default: change-me
    Description: "Your application name"
    Type: String
Resources:
  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName:
        Ref: ApplicationName
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      ServiceRoleArn: arn:aws:iam::019908562201:role/CodeDeploy_DemoApplication
      DeploymentGroupName: 
        Ref: DeploymentGroupName
      Ec2TagFilters:
      - Key: Name
        Type: KEY_AND_VALUE
        Value: 
          Ref: ApplicationName
